### ISSUE TITLE
MC 1.19.2 Repurposed Structures issue

### ISSUE THREAD

**Issue by kingstairs** [FinnSetchell/MoogsEndStructures#3]
Both the current and previous releases generate errors in the log regard Repurposed Structures:

```
[20:28:40] [Server thread/ERROR]: (Moog's End Structures pool_additions MERGER) Couldn't parse data file repurposed_structures:villages/badlands/houses from repurposed_structures:pool_additions/villages/badlands/houses.json
net.minecraft.class_3266: 'data/repurposed_structures/pool_additions/villages/badlands/houses.json' in ResourcePack 'C:\Games\MultiMC\instances\1.19.2 FO v2\.minecraft\config\paxi\datapacks\Repurposed_Structures-Better_Dungeons_v4.zip'
	at net.minecraft.class_3258.method_14391(class_3258.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14405(class_3255.java:38) ~[client-intermediary.jar:?]
	at com.finndog.mes.utils.GeneralUtils.getAllFileStreams(GeneralUtils.java:247) ~[mes-1.3-1.19.2-fabric.jar:?]
	at com.finndog.mes.utils.GeneralUtils.getAllDatapacksJSONElement(GeneralUtils.java:273) ~[mes-1.3-1.19.2-fabric.jar:?]
	at com.finndog.mes.misc.pooladditions.PoolAdditionMerger.mergeAdditionPools(PoolAdditionMerger.java:50) ~[mes-1.3-1.19.2-fabric.jar:?]
	at com.finndog.mes.MESCommon.serverAboutToStart(MESCommon.java:43) ~[mes-1.3-1.19.2-fabric.jar:?]
	at com.finndog.mes.events.base.EventHandler.invoke(EventHandler.java:25) ~[mes-1.3-1.19.2-fabric.jar:?]
	at com.finndog.mes.fabric.MESFabric.lambda$onInitialize$0(MESFabric.java:19) ~[mes-1.3-1.19.2-fabric.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:38) ~[fabric-lifecycle-events-v1-2.2.4+1b46dc7890-cde405b3e4280340.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bhm000$fabric-lifecycle-events-v1$beforeSetupServer(MinecraftServer.java:2796) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[20:28:40] [Server thread/ERROR]: (Moog's End Structures pool_additions MERGER) Couldn't parse data file repurposed_structures:villages/birch/houses from repurposed_structures:pool_additions/villages/birch/houses.json
net.minecraft.class_3266: 'data/repurposed_structures/pool_additions/villages/birch/houses.json' in ResourcePack 'C:\Games\MultiMC\instances\1.19.2 FO v2\.minecraft\config\paxi\datapacks\Repurposed_Structures-Better_Dungeons_v4.zip'
	at net.minecraft.class_3258.method_14391(class_3258.java:49) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14405(class_3255.java:38) ~[client-intermediary.jar:?]
	at com.finndog.mes.utils.GeneralUtils.getAllFileStreams(GeneralUtils.java:247) ~[mes-1.3-1.19.2-fabric.jar:?]
	at com.finndog.mes.utils.GeneralUtils.getAllDatapacksJSONElement(GeneralUtils.java:273) ~[mes-1.3-1.19.2-fabric.jar:?]
	at com.finndog.mes.misc.pooladditions.PoolAdditionMerger.mergeAdditionPools(PoolAdditionMerger.java:50) ~[mes-1.3-1.19.2-fabric.jar:?]
	at com.finndog.mes.MESCommon.serverAboutToStart(MESCommon.java:43) ~[mes-1.3-1.19.2-fabric.jar:?]
	at com.finndog.mes.events.base.EventHandler.invoke(EventHandler.java:25) ~[mes-1.3-1.19.2-fabric.jar:?]
	at com.finndog.mes.fabric.MESFabric.lambda$onInitialize$0(MESFabric.java:19) ~[mes-1.3-1.19.2-fabric.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:38) ~[fabric-lifecycle-events-v1-2.2.4+1b46dc7890-cde405b3e4280340.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bhm000$fabric-lifecycle-events-v1$beforeSetupServer(MinecraftServer.java:2796) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
(I only included the first couple of errors; the rest were similar)
I have not yet visited the End, so I don't know if these errors have any actual impact.

There is no "pool_additions" or "villages" folder in the data pack (which is a YUNG's/RS compatibility pack), so I don't understand what the mod is looking for...

- **Mod version:** 1.3 (also previous version)
- **Minecraft Version:** 1.19.2
- **Loader:** Fabric (API 0.76.1, Loader 0.14.22)
- **Java:** Adoptium 17.0.8.1

**Comment by FinnSetchell** [comment]
Ah thanks. And shouldnt create any problems for your game
